DROP TABLE IF EXISTS TBL_PRODUCT;
 
CREATE TABLE TBL_PRODUCT (
  product_id INT AUTO_INCREMENT  PRIMARY KEY,
  product_name VARCHAR(250) NOT NULL,
  product_price NUMBER NOT NULL,
  avail_quantity VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS TBL_CUSTOMER;
 
CREATE TABLE TBL_CUSTOMER (
  customer_id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  contact_number NUMBER NOT NULL
);

DROP TABLE IF EXISTS TBL_PRODUCT_BOOKING;

CREATE TABLE TBL_PRODUCT_BOOKING (
  billing_id INT AUTO_INCREMENT  PRIMARY KEY,
  customer_id INTEGER NOT NULL,
  product_details VARCHAR(300) NOT NULL,
  billing_comments VARCHAR(300) NOT NULL,
  billing_date DATE,
  total_price NUMBER NOT NULL  
);